### ISSUE TITLE
All in one is missing libpng16-16__.dll for avif

### ISSUE THREAD

**Issue by BuyMyMojo** [jialiang/ShitCompressor#1]
![Missing dll](https://s3.buymymojo.net/ShareX/2022/08/04/17/3SbR6D8jV2.png)

**Comment by jialiang** [comment]
Hi

It seems I accidentally compiled libavif to use local libraries I have installed on my PC.
I made a new release that should fix this issue.

**Comment by BuyMyMojo** [comment]
That fixed it, thanks!
